feign:
  url:
    prefix: http://localhost:8080/target_server #DemoFeignClient?? ??? url prefix
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 3000
        logger-level: NONE
      demo-client: #? custom FeignClient (DemoFeignClient)
        connect-timeout: 1000
        read-timeout: 10000
        logger-level: HEADERS